name: diffusion_sindy
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - numpy=1.24.3
  - matplotlib=3.7.2
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - tqdm=4.65.0
  - pip
  - pip:
    - pysindy==1.7.5
    - seaborn==0.12.2